---
- name: Install required system packages for Docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-apt
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - unzip
    - jq
    - python-pip

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Verify that we have the right key fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Get OS sub-type information
  shell: 'lsb_release -cs'
  register: os_sub_type_shell_output

- name: Set OS sub-type to a variable
  set_fact: os_sub_type="{{ os_sub_type_shell_output.stdout }}"

- name: Add Docker's Debian Repository
  apt_repository:
    repo: "deb {{ url_docker_debian_pkg }} {{ os_sub_type }} stable"
    state: present

- name: Install Docker (latest version)
  apt: 
    name: docker-ce
    update_cache: yes
    state: latest

- name: Ensure "docker" group exists
  group:
    name: docker
    state: present

- name: Add remote user to "docker" group
  user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: yes

# This is required for running Ansible docker-* modules
- name: Install Docker Module for Python
  pip:
    name:
      - pyrsistent==0.16.0
      - docker
      - docker-compose 

- name: Make sure "systemd" is used as the cgroup driver for Docker (for improved system stability)
  copy:
    dest: "/etc/docker/daemon.json"
    content: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
- name: Restart docker
  systemd:
    name: docker
    state: reloaded